imports:
  - php

before_commands:
  - composer install -n
  - composer dumpautoload -o

filter:
    paths: [src/*]
    excluded_paths: [vendor/*, tests/*, app/*, build/*, temp/*, doc/*]

tools:
    external_code_coverage:
        timeout: 600
    php_analyzer: true
    php_code_sniffer:
        config:
            ruleset: config/ruleset.xml
    php_cs_fixer: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    sensiolabs_security_checker: true
    php_changetracking: true
    php_sim: true    