language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - composer install --no-dev
  - php app/install.php
script:
  - phpunit --coverage-clover="temp/coverage.clover"
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover "temp/coverage.clover"